### PR TITLE
Replace CodeDropdown with ComputationalResourcesWidget.

### LINKED ISSUE #122: Use computational resources widget to setup codes/computers
The old approach is deprecated and is going to be removed by the next release of AWB.

### PR DESCRIPTION
**Pull request by yakutovicha**
fixes #122

### CODE REVIEW

**Comment by yakutovicha** [comment]
@cpignedoli, please test before approving.

**Review by cpignedoli — CHANGES_REQUESTED** [review]
Submission of NEB crashes, all other apps seem to work
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/apps/surfaces/reactions/neb_details.py in on_setup_btn_press(b)
     99                 clear_output()
    100 
--> 101                 if self.code_drop_down.selected_code is None:
    102                     print("please select a computer")
    103                     self.setup_success = False

AttributeError: 'ComputationalResourcesWidget' object has no attribute 'selected_code'

**Comment by yakutovicha** [comment]
@cpignedoli please try again.

**Review by cpignedoli — APPROVED** [review]
tested on local instances, no bugs found

**Pull request merged**
